### ISSUE TITLE
Non-zero code: 127

### ISSUE THREAD

**Issue by SugarfreeTX** [martindsouza/docker-ords#11] opened 2018-09-30 05:53 UTC
Hi Martin,

I am new to containers and docker. I am getting this error when trying to complete the Build ORDS Docker Image:

Step 6/11 : RUN chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh
 ---> Running in e194efdc293d
/bin/sh: /tmp/docker-run.sh: not found
The command '/bin/sh -c chmod +x /tmp/docker-run.sh &&   /tmp/docker-run.sh' returned a non-zero code: 127

I don't think I've missed any steps. I am on Windows 10 Home Edition. Is the OS my issue? 

Thanks,
Khemra

**Comment by martindsouza** [comment] 2018-09-30 23:11
@SugarfreeTX Can you please past the command you used for `docker run - ...`? I think it may be how you mounted the volumes which will be difference since you are running in Windows.

**Comment by SugarfreeTX** [comment] 2018-10-02 04:16
Hi Martin,

I'm using this:
`docker build -t ords:18.2.0 .`

When I used that today, I am getting a connectivity error. I turned off my VPN and same thing.

`error during connect: Post https://192.168.99.100:2376/v1.37/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=797530c720022200df511ba2581ddd0662a459bd6a053f44918451b292a57054&shmsize=0&t=ords%3A18.2.0&target=&ulimits=null: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

Thanks, hope it's not too much trouble. I am trying to run Apex so I can use Apex Nitro.

**Comment by Vikas-Kshirsagar** [comment] 2019-01-03 17:27
Hi Martin,

I am running through the same issue like @SugarfreeTX while using Window 10 Home version with Docker Toolbox. Previously I used this script on the Enterprise version and it went through smoothly. 

What I can see here is the **COPY ["ords.war", "scripts/*", "/tmp/"]** is not copying the files in tmp folder. Not sure If I am missing on any errors before that command or I can use any other way to check if Dockerfile is working correctly.

Thanks,
-Vikas

**Comment by aurelo** [comment] 2019-01-04 12:51
### 127 error ###
I've got "returned a non-zero code: 127" error. The problem is, as far as I can tell, that scripts: docker-run.sh and config-run-ords.sh are cloned with Windows (CR LF) line break instead of unix (LF) on windows machines.  Scripts are copied to container but can not be executed because of incorrect line break.
**Solution:** open scripts on host machine in i.e. notepad++ and change line break to unix then build image again.

### connectivity error ###
If you're behind proxy, you'll need to add and set up http_proxy and https_proxy environment variables in Dockerfile: replace yourcompanyproxy accordingly
```
  TOMCAT_HOME="/usr/local/tomcat" \
  HTTP_PROXY=yourcompanyproxy \
  HTTPS_PROXY=yourcompanyproxy \
  APEX_PUBLIC_USER_NAME="APEX_PUBLIC_USER" \
```

**Comment by martindsouza** [comment] 2019-02-22 13:39
Closing as not supporting Windows. This is build for Windows.

**Closed as completed by martindsouza** 2019-02-22 13:39 UTC
Labels: question
